plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.audioplayback'
version = '1.0.0'

android {
  namespace 'expo.modules.audioplayback'
  ndkVersion rootProject.ext.ndkVersion
  buildFeatures { prefab true }
  defaultConfig {
    versionCode 1
    versionName '1.0.0'
    externalNativeBuild {
      cmake { arguments '-DANDROID_STL=c++_shared' }
    }
  }
  externalNativeBuild {
    cmake { path 'src/main/cpp/CMakeLists.txt'; version '3.22.1' }
  }
}

dependencies {
  implementation 'com.google.oboe:oboe:1.9.3'
}
